### ISSUE TITLE
Activation: Host function requirements

### ISSUE THREAD

**Issue by bbyalcinkaya** [runtimeverification/komet#1]
## TODO 
The following host functions are required for executing the `FxDAO/vaults` contract's `calculate_deposit_ratio`, `get_core_state`, and `set_admin` endpoints.

- [x] `obj_from_u128_pieces`: #12 
- [x] `obj_to_u128_lo64`: #12
- [x] `obj_to_u128_hi64`: #12
- [x] `vec_new_from_linear_memory`: #13 
- [x] `symbol_new_from_linear_memory`: #13 
- [x] `map_unpack_to_linear_memory`: #15 
- [x] `map_new_from_linear_memory`: #15 
- [x] `get_ledger_sequence`: #16 
- [x] `fail_with_error`: #26 
- [x] `put_contract_data`: #18 
- [x] `has_contract_data`: #18 
- [x] `get_contract_data`: #18 
- [x] `extend_current_contract_instance_and_code_ttl`: #24 
- [x] `require_auth`: #27 

## Prerequisites

All function arguments and results are passed as 64-bit integers representing primitive values or **host value types** in the format described in [CAP 46-01](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-01.md#host-value-type). Host values are tagged union of primitive types or complex objects like buffers, big integers, vectors, maps etc.

[CAP 46-03 - Parameter types and nomenclature](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-03.md#parameter-types-and-nomenclature)
[CAP 46-01 - Host value type](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-01.md#host-value-type)

## Host functions

Host functions are grouped into logical modules. Every module has a single character identifier. Likewise, every host function in a module is identified with a single character. For example `(import "x" "3" (func (type 6)))` imports the `get_ledger_sequence` function from the context module.

| Module | Name | Identifier |
| ----------- | --------- | -------------- |
| Context | `get_ledger_sequence` | `"x" "3"` |
| Context | `fail_with_error` | `"x" "5"` |
| Int | `obj_from_u128_pieces` | `"i" "3"` |
| Int | `obj_to_u128_lo64` | `"i" "4"` |
| Int | `obj_to_u128_hi64` | `"i" "5"` |
| Map | `map_new_from_linear_memory` | `"m" "9"` |
| Map | `map_unpack_to_linear_memory` | `"m" "a"` |
| Vec | `vec_new_from_linear_memory` | `"v" "g"` |
| Ledger | `put_contract_data` | `"l" "_"` |
| Ledger | `has_contract_data` | `"l" "0"` |
| Ledger | `get_contract_data` | `"l" "1"` |
| Ledger | `extend_current_contract_instance_and_code_ttl` | `"l" "8"` |
| Buf | `symbol_new_from_linear_memory` | `"b" "j"` |
| Address | `require_auth` | `"a" "0"` |

### Context

Identifier: `x`

<details>

#### `get_ledger_sequence`

Identifier: `3`

Type:
```rust
() -> U32Val
```

Return the sequence number of the current ledger as a u32.

#### `fail_with_error`

Identifier: `5`

Type:
```rust
(error: Error) -> Void
```

Causes the currently executing contract to fail immediately with a provided error code, which must be of error-type `ScErrorType::Contract`. Does not actually return.

</details>

### Int

Identifier: `i`

<details>

#### `obj_from_u128_pieces`

Identifier: `3`

Type:
```rust
(hi: u64, lo: u64) -> U128Object
```

Convert the high and low 64-bit words of a u128 to an object containing a u128.

#### `obj_to_u128_lo64`

Identifier: `4`

Type:
```rust
(obj: U128Object) -> u64
```

Extract the low 64 bits from an object containing a u128.

#### `obj_to_u128_hi64`

Identifier: `5`

Type:
```rust
(obj: U128Object) -> u64
```

Extract the high 64 bits from an object containing a u128.

</details>

### Map

Identifier: `m`

<details>

#### `map_new_from_linear_memory`

Identifier: `9`

Type:
```rust
(keys_pos: U32Val, vals_pos: U32Val, len: U32Val) -> MapObject
```

Return a new map initialized from a pair of equal-length arrays, one for keys and one for values, given by a pair of linear-memory addresses and a length in Vals.

#### `map_unpack_to_linear_memory`

Identifier: `a`

Type:
```rust
(map: MapObject, keys_pos: U32Val, vals_pos: U32Val, len: U32Val) -> Void
```

Copy Vals from `map` to the array `vals_pos`, selecting only the keys identified by the array `keys_pos`. Both arrays have `len` elements and are identified by linear-memory addresses.

</details>

### Vec

Identifier: `v`

<details>

#### `vec_new_from_linear_memory`

Identifier: `g`

Type:
```rust
(vals_pos: U32Val, len: U32Val) -> VecObject
```

Return a new vec initialized from an input slice of Vals given by a linear-memory address and length in Vals.

</details>

### Ledger

Identifier: `l`

<details>

#### `put_contract_data`

Identifier: `_`

Type:
```rust
(k: Val, v: Val, t: StorageType) -> Void
```

#### `has_contract_data`

Identifier: `0`

Type:
```rust
(k: Val, t: StorageType) -> Bool
```

#### `get_contract_data`

Identifier: `1`

Type:
```rust
(k: Val, t: StorageType) -> Val
```

#### `extend_current_contract_instance_and_code_ttl`

Identifier: `8`

Type:
```rust
(threshold: U32Val, extend_to: U32Val) -> Void
```

If the TTL for the current contract instance and code (if applicable) is below `threshold` ledgers, extend `live_until_ledger_seq` such that TTL == `extend_to`, where TTL is defined as live_until_ledger_seq - current ledger. If attempting to extend past the maximum allowed value (defined as the current ledger + `max_entry_ttl` - 1), the new `live_until_ledger_seq` will be clamped to the max.

</details>

### Buf

Identifier: `b`

<details>

#### `symbol_new_from_linear_memory`

Identifier: `j`

Type:
```rust
(lm_pos: U32Val, len: U32Val) -> SymbolObject
```

Constructs a new `Symbol` object initialized with bytes copied from a linear memory slice specified at position `lm_pos` with length `len`.

</details>

### Address

Identifier: `a`

<details>

#### `require_auth`

Identifier: `0`

Type:
```rust
(address: AddressObject) -> Void
```

Checks if the address has authorized the invocation of the current contract function with all the arguments of the invocation. Traps if the invocation hasn't been authorized.

</details>
